POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Esse é o vídeo 01",
    "duration": 180
}

###

GET http://localhost:3333/videos?search=01
Content-Type: application/json

###


GET http://localhost:3333/videos
Content-Type: application/json

###     

PUT http://localhost:3333/videos/f9bc8f2a-5628-4757-b65d-7b963ad53e30
Content-Type: application/json

{
    "title": "Videos 02",
    "description": "Esse é o vídeo 02",
    "duration": 180
}
###

DELETE  http://localhost:3333/videos/f9bc8f2a-5628-4757-b65d-7b963ad53e30
Content-Type: application/json